// <auto-generated />
using System;
using Fontana.AI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fontana.AI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722120005_AddWineAssortmentType")]
    partial class AddWineAssortmentType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fontana.AI.Models.ConversationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BotResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Feedback")
                        .HasColumnType("bit");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConversationLogs");
                });

            modelBuilder.Entity("Fontana.AI.Models.DabasProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gtin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nutrition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DabasProducts");
                });

            modelBuilder.Entity("Fontana.AI.Models.FaqItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Fontana är ett familjeföretag med rötter i Grekland och Cypern. Våra produkter är noga utvalda från Medelhavsregionen.",
                            Category = "Allmänt",
                            Question = "Var kommer Fontanas produkter ifrån?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Ja, vår extra virgin olivolja är kallpressad för att bevara smak och naturliga näringsvärden.",
                            Category = "Produkter",
                            Question = "Är Fontanas olivolja kallpressad?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Våra produkter finns i de flesta svenska livsmedelsbutiker. Kontakta oss på info@fontanafood.se om du inte hittar dem nära dig.",
                            Category = "Inköp",
                            Question = "Var kan jag köpa Fontanas produkter?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Förvara olivoljan svalt och mörkt, gärna i rumstemperatur och borta från direkt solljus. Undvik kylskåp då oljan kan stelna.",
                            Category = "Förvaring",
                            Question = "Hur ska jag förvara olivoljan?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Vissa av våra produkter är ekologiskt certifierade. Se produktetiketten eller kontakta oss på info@fontanafood.se för mer information.",
                            Category = "Certifiering",
                            Question = "Är era produkter ekologiska?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "De flesta av våra produkter är glutenfria, men vi rekommenderar alltid att du kontrollerar ingrediensförteckningen på förpackningen för säkerhets skull.",
                            Category = "Allergener",
                            Question = "Innehåller era produkter gluten?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Du når oss enklast via e-post på info@fontanafood.se. Vi svarar så snart vi kan.",
                            Category = "Kontakt",
                            Question = "Hur kontaktar jag Fontana?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Vi rekommenderar att olivoljan används inom 3–6 månader efter öppning för bästa smak. Se alltid bäst-före-datum på förpackningen.",
                            Category = "Förvaring",
                            Question = "Hur länge håller olivoljan efter öppning?"
                        },
                        new
                        {
                            Id = 9,
                            Answer = "Nej, vi säljer alkoholhaltiga drycker endast till restauranger och foodservice-kunder — inte direkt till privatpersoner, det är inte tillåtet enligt svensk lag. Vill du som privatperson få tag på ett specifikt vin eller sprit ur vårt sortiment kan du kontakta Systembolagets avdelning för speciella viner och sprit och begära en så kallad privatimport. Systembolaget skickar då en förfrågan vidare till oss, och vi lämnar i så fall ett pris till dem — inte till dig direkt. Det går inte att köpa varan via en restaurang istället.",
                            Category = "Vin & Alkohol",
                            Question = "Kan jag som privatperson köpa vin eller sprit direkt av Fontana?"
                        },
                        new
                        {
                            Id = 10,
                            Answer = "Vår halloumi tillverkas med mikrobiell löpe (ystenzym) som framställs med hjälp av mikroorganismen Rhizomucor miehei — inte animalisk löpe (som annars utvinns ur magen hos unga kalvar, lamm eller killingar). Båda typerna av löpe har samma funktion i osttillverkningen: att få mjölken att koagulera så att ost kan bildas. Skillnaden ligger i hur enzymet framställs, och det påverkar normalt inte halloumins smak eller användningsområde på ett märkbart sätt. Eftersom vår halloumi använder mikrobiell löpe är den helt vegetarisk och passar därför fler konsumenter.",
                            Category = "Ingredienser",
                            Question = "Använder ni animalisk eller mikrobiell löpe i er halloumi?"
                        },
                        new
                        {
                            Id = 11,
                            Answer = "Börja med att tina paketet oöppnat i kylskåp över natten. Låt det sedan ligga i rumstemperatur i 20–30 minuter innan användning, fortfarande oöppnat. När paketet väl är öppnat, ta ett eller några ark i taget och lägg en fuktig kökshandduk över de övriga arken — filodeg torkar och smular lätt sönder annars, både färsk och fryst.",
                            Category = "Tillagning & Hantering",
                            Question = "Hur tinar jag er frysta filodeg utan att den går sönder?"
                        });
                });

            modelBuilder.Entity("Fontana.AI.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainIngredient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occasion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Fontana.AI.Models.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlcoholPercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssortmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystembolagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wines");
                });
#pragma warning restore 612, 618
        }
    }
}
