// <auto-generated />
using Fontana.AI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fontana.AI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304143645_SeedFaqData")]
    partial class SeedFaqData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fontana.AI.Models.FaqItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Fontana är ett familjeföretag med rötter i Grekland och Cypern som importerar och säljer autentiska medelhavsdelikatesser till den svenska marknaden. Vi brinner för äkta smaker och hög kvalitet.",
                            Category = "Om oss",
                            Question = "Vad är Fontana?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Fontanas produkter finns i välsorterade livsmedelsbutiker runt om i Sverige. Kontakta din lokala butik för att höra om de har Fontanas sortiment.",
                            Category = "Om oss",
                            Question = "Var kan jag köpa Fontanas produkter?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Du är välkommen att kontakta oss på fontana@support.com så hjälper vi dig så snart vi kan!",
                            Category = "Om oss",
                            Question = "Hur kontaktar jag Fontana?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Halloumi innehåller mjölk (get- och/eller fårmjölk). Produkten är inte lämplig för personer med mjölkallergi eller laktosintolerans.",
                            Category = "Allergener",
                            Question = "Vilka allergener finns i halloumi?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Traditionell halloumi är gjord på pastöriserad get- och/eller fårmjölk, salt och mynta. Inga onödiga tillsatser.",
                            Category = "Ingredienser",
                            Question = "Vad innehåller halloumi för ingredienser?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "Halloumi är en traditionell ost med ursprung på Cypern och är en skyddad ursprungsbeteckning (PDO) inom EU sedan 2021.",
                            Category = "Ursprung",
                            Question = "Var kommer halloumin ifrån?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Ja! Halloumi är perfekt för grillning. Den smälter inte utan får en fin stekyta och krämig insida. Grilla på hög värme i 2–3 minuter per sida.",
                            Category = "Tillagning",
                            Question = "Kan man grilla halloumi?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Ja, halloumi är vegetarisk. Den innehåller inga kött- eller fiskprodukter.",
                            Category = "Kost",
                            Question = "Är halloumi vegetarisk?"
                        },
                        new
                        {
                            Id = 9,
                            Answer = "Fetaost innehåller mjölk (fårmjölk, ibland upp till 30% getmjölk). Inte lämplig för personer med mjölkallergi.",
                            Category = "Allergener",
                            Question = "Vilka allergener finns i fetaost?"
                        },
                        new
                        {
                            Id = 10,
                            Answer = "Äkta fetaost är en skyddad ursprungsbeteckning (PDO) och tillverkas uteslutande i Grekland. Den görs på fårmjölk eller en blandning av får- och getmjölk.",
                            Category = "Ursprung",
                            Question = "Var kommer fetaosten ifrån?"
                        },
                        new
                        {
                            Id = 11,
                            Answer = "Fetaost innehåller pastöriserad fårmjölk (ibland upp till 30% getmjölk) och salt. Lagras i saltlake för sin karakteristiska smak.",
                            Category = "Ingredienser",
                            Question = "Vad innehåller fetaost?"
                        },
                        new
                        {
                            Id = 12,
                            Answer = "Ja, fetaost är vegetarisk och innehåller inga kött- eller fiskprodukter.",
                            Category = "Kost",
                            Question = "Är fetaost vegetarisk?"
                        },
                        new
                        {
                            Id = 13,
                            Answer = "Fontana erbjuder extra virgin olivolja av hög kvalitet med ursprung från Medelhavsregionen. Extra virgin innebär att oljan är kallpressad och av högsta kvalitetsklass.",
                            Category = "Produktinfo",
                            Question = "Vilken olivolja säljer Fontana?"
                        },
                        new
                        {
                            Id = 14,
                            Answer = "Ren olivolja innehåller inga kända allergener. Den är naturligt fri från gluten, mjölk, nötter och soja.",
                            Category = "Allergener",
                            Question = "Vilka allergener finns i olivolja?"
                        },
                        new
                        {
                            Id = 15,
                            Answer = "Många av Fontanas produkter som ostar och olivolja är naturligt glutenfria. Kontrollera alltid förpackningens innehållsförteckning för den specifika produkten eller kontakta oss på fontana@support.com.",
                            Category = "Kost",
                            Question = "Är Fontanas produkter glutenfria?"
                        },
                        new
                        {
                            Id = 16,
                            Answer = "Fontana strävar efter att erbjuda naturliga och högkvalitativa produkter. För information om specifika ekologiska produkter, kontakta oss på fontana@support.com.",
                            Category = "Produktinfo",
                            Question = "Säljer Fontana ekologiska produkter?"
                        },
                        new
                        {
                            Id = 17,
                            Answer = "Halloumi och fetaost förvaras bäst i kylskåp. Öppnad förpackning bör användas inom några dagar. Fetaost kan förvaras i saltlake för längre hållbarhet.",
                            Category = "Förvaring",
                            Question = "Hur förvarar jag halloumi och fetaost?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
