// <auto-generated />
using System;
using Fontana.AI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fontana.AI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720110238_AddWines")]
    partial class AddWines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fontana.AI.Models.ConversationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BotResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Feedback")
                        .HasColumnType("bit");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConversationLogs");
                });

            modelBuilder.Entity("Fontana.AI.Models.DabasProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gtin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nutrition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DabasProducts");
                });

            modelBuilder.Entity("Fontana.AI.Models.FaqItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Fontana är ett familjeföretag med rötter i Grekland och Cypern. Våra produkter är noga utvalda från Medelhavsregionen.",
                            Category = "Allmänt",
                            Question = "Var kommer Fontanas produkter ifrån?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Ja, vår extra virgin olivolja är kallpressad för att bevara smak och naturliga näringsvärden.",
                            Category = "Produkter",
                            Question = "Är Fontanas olivolja kallpressad?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Våra produkter finns i de flesta svenska livsmedelsbutiker. Kontakta oss på fontana@support.com om du inte hittar dem nära dig.",
                            Category = "Inköp",
                            Question = "Var kan jag köpa Fontanas produkter?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Förvara olivoljan svalt och mörkt, gärna i rumstemperatur och borta från direkt solljus. Undvik kylskåp då oljan kan stelna.",
                            Category = "Förvaring",
                            Question = "Hur ska jag förvara olivoljan?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Vissa av våra produkter är ekologiskt certifierade. Se produktetiketten eller kontakta oss på fontana@support.com för mer information.",
                            Category = "Certifiering",
                            Question = "Är era produkter ekologiska?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "De flesta av våra produkter är glutenfria, men vi rekommenderar alltid att du kontrollerar ingrediensförteckningen på förpackningen för säkerhets skull.",
                            Category = "Allergener",
                            Question = "Innehåller era produkter gluten?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Du når oss enklast via e-post på fontana@support.com. Vi svarar så snart vi kan.",
                            Category = "Kontakt",
                            Question = "Hur kontaktar jag Fontana?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Vi rekommenderar att olivoljan används inom 3–6 månader efter öppning för bästa smak. Se alltid bäst-före-datum på förpackningen.",
                            Category = "Förvaring",
                            Question = "Hur länge håller olivoljan efter öppning?"
                        });
                });

            modelBuilder.Entity("Fontana.AI.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainIngredient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occasion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Fontana.AI.Models.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlcoholPercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystembolagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wines");
                });
#pragma warning restore 612, 618
        }
    }
}
